name: makemonday
favicon: null
layout_spectrum: 0.3711941840592772
typography_spectrum: 0.47898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.728651637211442
  lightness: 0.5250325712841004
  saturation: 0.39065300044603646
  rhythmicContrast: 0.3883177638053894
purpose: []
