name: makemonday
favicon: null
layout_spectrum: 0.07968
typography_spectrum: 0.26507
title: A small and modest press lab in the heart of Seoul.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11323d'
    - '#fefefc'
    - '#71848c'
    - '#4a5457'
    - '#c2988f'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
