name: makemonday
favicon: null
layout_spectrum: 0.11463
typography_spectrum: 0.1369
title: A small and modest press lab in the heart of Seoul.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11323d'
    - '#fefefc'
    - '#71848c'
    - '#4a5457'
    - '#c2988f'
  brandStrength: 0.728651637211442
  lightness: 0.5250325712841004
  saturation: 0.39065300044603646
  rhythmicContrast: 0.3883177638053894
purpose: []
